const { mock } = require('sao');
const test = require('ava');
const path = require('path')

const generator = path.join(__dirname);

test.beforeEach(async t => {
	t.context.stream = await mock({ generator });
})

test('generator with default answers', t => {
	const stream = t.context.stream;
	const packageJson = stream.readFile('package.json');
	const rollup = stream.readFile('rollup.config.json');
	console.log(packageJson);
	t.is(packageJson.description, 'generated by sao-wm');
})
