const validateLicense = require('validate-npm-package-license')
const assert = require('assert')

const validate = function (license) {
	const validSPDXExpression = {
		validForNewPackages: true,
		validForOldPackages: true,
		spdx: true
	};
	try {
		assert.deepEqual(validateLicense(license), validSPDXExpression)
		return true
	} catch (e) {
		return false
	}
}

module.exports = {
	prompts() {
		return [
			{
				name: 'name',
				message: 'The name of your project',
				default: this.outFolder,
				filter: val => val.toLowerCase()
			},
			{
				name: 'description',
				message: 'The description of your project',
				default: 'generated by sao-wm'
			},
			{
				name: 'license',
				message: 'The license of your project',
				default: 'MIT',
				filter: val => {
					return validate(val)?val:'MIT'
				}
			},
			{
				name: 'author',
				default: this.gitUser.name || this.gitUser.username,
				store: true
			},
			{
				name: 'sourcemap',
				message: 'Do you need to generate sourcemap for your project?',
				type: 'confirm',
				default: true
			}
		]
	},
	actions() {
		return [
			{
				type: 'add',
				files: '**'
			}
		]
	},
	async completed() {
		this.gitInit()
		await this.npmInstall()
		this.showProjectTips()
	}
}
